apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argocd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/shivamsingh3238/argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: leaveplanner

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true