apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivamsingh3238/argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: leaveplanner

  syncPolice:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true