#NameSpace
apiVersion: v1
kind: Namespace
metadata:
  name: leaveplanner

#Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-backend
  namespace: leaveplanner
  labels:
    app: application
    type: backend
spec:
  template:
    metadata:
      labels:
        name: leaveplanner
        type: backend
    spec:
      containers:
        - name: leaveplanner-backend-images
          image: shivamsinghgslab/application-backend-k8s
          ports:
            - containerPort: 3000
  replicas: 3
  selector:
    matchLabels:
      name: leaveplanner
      type: backend

---
#Services
apiVersion: v1
kind: Service
metadata:
  name: application-backend-services
  namespace: leaveplanner 
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 3000
    nodePort: 30011
  selector:
    name: leaveplanner
    type: backend

