name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    
    - name: featch version
      id: v1 
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        version=${GITHUB_REF##*/}-$git_hash
        echo $version

    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: shivamsinghgslab/application-ui-k8s
        registry: docker.io
        dockerfile: Dockerfile
        tags: ${{ steps.v1.version }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Update Version
      run: |
          version=$(cat ./charts/helm-example/values.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/${{ steps.v1.version }}" /dev/application//values.yaml

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated