name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_USERNAME }}

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: build and push docker images
    #   id: image-push
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-docker.outputs.registry }}
    #     ECR_REPOSITORY: application-ui-k8s

    #   run: |
    #     # Build a docker container and push to dockerhub 
    #     git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash .
    #     echo "Pushing image to Dockerhub..."
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash

    
