name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    
    - name: featch version
      id: v1 
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        version=${GITHUB_REF##*/}-$git_hash
        echo $version

    # - name: Build the Docker image
    #   uses: mr-smithers-excellent/docker-build-push@v5
    #   with:
    #     image: shivamsinghgslab/application-ui-k8s
    #     registry: docker.io
    #     dockerfile: Dockerfile
    #     tags: ${{ steps.v1.version }}
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
